# Generated by Django 4.1 on 2024-02-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CancertType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gene_name", models.CharField(max_length=50)),
                ("start_position", models.IntegerField()),
                ("end_position", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MoleculeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Organ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sex", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("race", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceGenome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("genome_size", models.IntegerField()),
                ("url", models.URLField()),
                ("build_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organ",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="variation.organ",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variation.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Study_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abstract", models.CharField(max_length=2000)),
                ("findings", models.CharField(max_length=1000)),
                ("doi", models.CharField(max_length=100)),
                ("references", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tissue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="StudySample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cancer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variation.cancerttype",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variation.sample",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variation.study_1",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="study_1",
            name="study_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="variation.studytype"
            ),
        ),
        migrations.CreateModel(
            name="Snpmutant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="variation.gene"
                    ),
                ),
                (
                    "molecular_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variation.moleculeprofile",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variation.sample",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SNP_Mutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="variation.gene"
                    ),
                ),
                (
                    "molecular_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variation.moleculeprofile",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variation.sample",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="variation.sampletype"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="tissue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="variation.tissue"
            ),
        ),
        migrations.AddField(
            model_name="cancerttype",
            name="reference_genome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="variation.referencegenome",
            ),
        ),
    ]
