# Generated by Django 4.1 on 2024-02-22 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("variation", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Study_1",
            new_name="Study",
        ),
    ]
